maciej_skorupa/blog/urls.py
from django.urls import path
from blog import views


app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('solo', views.solo, name='solo'),
    path('bohomaz', views.bohomaz, name='bohomaz'),
    path('petla', views.petla, name='petla'),
    path('kontakt', views.kontakt, name='kontakt'),
]

maciej_skorupa/maciej_skorupa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

maciej_skorupa/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


class Project(models.Model):
    name = models.CharField(max_length=200)
    create_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    post_text = models.TextField()
    video_address = models.TextField(null=True, blank=True)
    create_date = models.DateTimeField(default=timezone.now)
    project = models.ForeignKey(Project, on_delete=models.CASCADE,
                             related_name='projects', null=True, blank=True)
    publish = models.BooleanField(default=False)
    header = models.BooleanField(default=False, null=True, blank=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def get_absolute_url(self):
        return reverse("post_detail", kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

maciej_skorupa/blog/views.py
from django.shortcuts import render
from django.views.generic import DetailView
from blog.models import Post, Project

from django.core.mail import send_mail
from django.conf import settings


def index(request):
    post_list = Post.objects.filter(project__name='Strona glowna').order_by('create_date').reverse()
    context_dict = {'posts': post_list}
    return render(request, 'blog/index.html', context_dict)


def solo(request):
    header_list = Post.objects.filter(project__name='Solo', header=True).order_by('create_date').reverse()
    post_list = Post.objects.filter(project__name='Solo', header=False).order_by('create_date').reverse()
    context_dict = {'posts': post_list, 'headers': header_list}
    return render(request, 'blog/solo.html', context_dict)


def bohomaz(request):
    header_list = Post.objects.filter(project__name='Bohomaz', header=True).order_by('create_date').reverse()
    post_list = Post.objects.filter(project__name='Bohomaz', header=False).order_by('create_date').reverse()
    context_dict = {'posts': post_list, 'headers': header_list}
    return render(request, 'blog/bohomaz.html', context_dict)


def petla(request):
    header_list = Post.objects.filter(project__name='Petla', header=True).order_by('create_date').reverse()
    post_list = Post.objects.filter(project__name='Petla', header=False).order_by('create_date').reverse()
    context_dict = {'posts': post_list, 'headers': header_list}
    return render(request, 'blog/petla.html', context_dict)


def kontakt(request):
    if request.method == 'POST':
        email_imie = request.POST['email-imie']
        email_adres = request.POST['email-adres']
        email_text = request.POST['email-text']

        # send an email
        send_mail(
            email_imie + ' - ' + email_adres, # subject
            'Wiadomosc od: ' + email_imie+'\n' + 'Adres email: ' + email_adres +'\n\n' + email_text, # message
            email_adres, # from email
            ['tomidrapaa@gmail.com'], # to email
        )

        return render(request, 'blog/kontakt.html',
                      {'email_imie': email_imie})
    else:
        return render(request, 'blog/kontakt.html', {})

maciej_skorupa/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Maciej Skorupa</title>
    <!-- Bootstrap -->
    <!-- jQuery and Popper.js -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

    <!-- Compiled CSS and JS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- My CSS -->
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
    {% block additional_css %}
    {% endblock additional_css %}

    <!-- Font-Awesome -->
    <link href="{% static 'font_awesome/css/all.min.css' %}" rel="stylesheet">

  </head>

<body>
  {% block additional %}
  {% endblock additional %}

<section class="page-container">
  <div class="content-wrap">

    <header>
      <nav class="navbar-dim navbar navbar-expand-lg">
        <div class="navbar-custom container-fluid">

          <a class="logo navbar-brand" href="{% url 'blog:index' %}">Maciej Skorupa</a>

          <div class="nav-custom-right navbar-nav nav navbar-right">
            <ul class="nav">
              <li class="nav-item"><a class="nav-custom nav-link " href="{% url 'blog:solo' %}">Solo</a></li>
              <li class="nav-item"><a class="nav-custom nav-link " href="{% url 'blog:bohomaz' %}">Bohomaz</a></li>
              <li class="nav-item"><a class="nav-custom nav-link " href="{% url 'blog:petla' %}">Pętla</a></li>
              <li class="nav-item"><a class="nav-custom nav-link " href="{% url 'blog:kontakt' %}">Kontakt</a> </li>
              <li class="dropdown-custom nav-item dropdown">
                <a class="nav-custom nav-link dropdown-toggle " href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Social
                </a>
                <div class="dropdown-custom dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="https://www.youtube.com/channel/UCWLANMQZqpbk4on9cAAwZeA">YouTube</a>
                  <a class="dropdown-item" href="https://www.facebook.com/maciek.skorupa.5">FaceBook</a>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <div class="container">
      {% block body_block %}

      {% endblock body_block %}
    </div>

  </div>

    <footer class="footer">
        <ul class="footer-ul">
          <li>
            <a class="" href="https://www.youtube.com/channel/UCWLANMQZqpbk4on9cAAwZeA">
              <i class="fab fa-youtube fa-2x footer-icons yt"></i>
            </a>
          </li>
          <li>
            <a href="https://www.facebook.com/maciek.skorupa.5">
              <i class="fab fa-facebook fa-2x footer-icons fb"></i>
            </a>
          </li>
            </ul>
    </footer>

  </section>

</body>
</html>

maciej_skorupa/templates/blog/bohomaz.html
{% extends "blog/base.html" %}

{% block additional %}
  <div class="background_image" style="background-image: url(../static/images/karmelowa.jpg);">
{% endblock additional %}


{% block body_block %}

  {% for header in headers %}
  <div class="row justify-content-center">
    <h5 class="header-text col-10 col-sm-11 col-md-9 col-lg-9 text-center">
      {{ header.post_text }}
    </h5>
    <hr class="line-break-header">
  </div>
  {% endfor %}

  {% for post in posts %}

      {% if forloop.counter > 1 %}
        <hr class="line-break">
      {% endif %}
        <div class="row justify-content-center">
          <h5 class="text col-10 col-sm-11 col-md-9 col-lg-9 text-center">
            {{ post.post_text }}
          </h5>
          <!-- <h6 class="date col-12">{{ post.create_date }}</h6> -->
        </div>
      {% if post.video_address %}
          <iframe class="video" width=80% height="515"
          src="{{ post.video_address }}" frameborder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope;
          picture-in-picture" allowfullscreen></iframe>
      {% endif %}

  {% endfor %}

{% endblock body_block %}

maciej_skorupa/templates/blog/index.html
{% extends "blog/base.html" %}

{% block additional %}
  <div class="background_image" style="background-image: url(../static/images/front_1900.jpg);">
{% endblock additional %}


{% block body_block %}

    {% for post in posts %}
      <div class="row justify-content-center pt-5">
        <h4 class="col-10 col-sm-10 col-md-9 col-lg-10">
          <p class="front-text text-center">{{ post.post_text }}</p>
        </h4>
      </div>
      {% if post.video_address %}
          <iframe class="video" width=80% height="515"
          src="{{ post.video_address }}" frameborder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope;
          picture-in-picture" allowfullscreen></iframe>
      {% endif %}

    {% endfor %}



{% endblock body_block %}

maciej_skorupa/templates/blog/kontakt.html
<!DOCTYPE html>
{% extends "blog/base.html" %}

{% block additional_css %}
<link rel="stylesheet" href="static/css/kontakt/kontakt.css">
{% endblock additional_css %}

{% block additional %}
<div class="kontakt-nav">
{% endblock additional %}


{% block body_block %}

  {% if email_imie %}
    <div class="pt-5 pl-5">
      <h3 class="">Dzięki {{ email_imie }}!</h3>
      <h4>Otrzymałem Twoją wiadomość i odpowiem wkrótce.</h4>
    </div>
  {% else %}
    <form action="{% url 'blog:kontakt' %}" method="post">
      {% csrf_token %}
      <div class="form-group">
          <label for="exampleFormControlTextarea1">Twoje imię:</label>
          <textarea class="form-control" name="email-imie" rows="1" placeholder="Imię" required></textarea>
      </div>
      <div class="form-group">
          <label for="exampleInputEmail1">Twój adres email:</label>
          <input type="email" class="form-control" name="email-adres"  placeholder="Email" required>
      </div>
      <div class="form-group">
          <label for="exampleFormControlTextarea1">Wiadomość:</label>
          <textarea class="form-control" name="email-text" rows="3" required></textarea>
      </div>

      <button type="submit" class="btn btn-primary">Wyślij</button>
    </form>

  <div class="alter_email">Jeśli wolisz koszystać z własnej poczty email zapraszam do kontaktu pod adresem
    <strong>mskorupa.mailing@gmail.com</strong>
  </div>
  {% endif %}


{% endblock body_block %}

maciej_skorupa/templates/blog/petla.html
<!DOCTYPE html>
{% extends "blog/base.html" %}

{% block additional %}
  <div class="background_image" style="background-image: url(../static/images/petla.jpg);">
{% endblock additional %}


{% block body_block %}
  {% for header in headers %}
    <div class="row justify-content-center">
      <h5 class="header-text col-10 col-sm-11 col-md-9 col-lg-9 text-center">
        {{ header.post_text }}
      </h5>
      <hr class="line-break-header">
    </div>
  {% endfor %}

  {% for post in posts %}

      {% if forloop.counter > 1 %}
        <hr class="line-break">
      {% endif %}
        <div class="row justify-content-center">
          <h5 class="text col-10 col-sm-11 col-md-9 col-lg-9 text-center">
            {{ post.post_text }}
          </h5>
          <!-- <h6 class="date col-12">{{ post.create_date }}</h6> -->
        </div>
      {% if post.video_address %}
          <iframe class="video" width=80% height="515"
          src="{{ post.video_address }}" frameborder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope;
          picture-in-picture" allowfullscreen></iframe>
      {% endif %}

  {% endfor %}

{% endblock body_block %}

maciej_skorupa/templates/blog/solo.html
{% extends "blog/base.html" %}

{% block additional %}
  <div class="background_image" style="background-image: url(../static/images/solo_1900.jpg);">
{% endblock additional %}


{% block body_block %}
  
{% for header in headers %}
  <div class="row justify-content-center">
    <h5 class="header-text col-10 col-sm-11 col-md-9 col-lg-9 text-center">
      {{ header.post_text }}
    </h5>
    <hr class="line-break-header">
  </div>
  {% endfor %}

  {% for post in posts %}

      {% if forloop.counter > 1 %}
        <hr class="line-break">
      {% endif %}
        <div class="row justify-content-center">
          <h5 class="text col-10 col-sm-11 col-md-9 col-lg-9 text-center">
            {{ post.post_text }}
          </h5>
          <!-- <h6 class="date col-12">{{ post.create_date }}</h6> -->
        </div>
      {% if post.video_address %}
          <iframe class="video" width=80% height="515"
          src="{{ post.video_address }}" frameborder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope;
          picture-in-picture" allowfullscreen></iframe>
      {% endif %}

  {% endfor %}

{% endblock body_block %}